# Generated by Django 4.0.5 on 2022-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del tutor')),
                ('nommascota', models.CharField(max_length=20, verbose_name='Nombre de la mascota')),
                ('nomtutor', models.CharField(max_length=20, verbose_name='Nombre del tutor')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion del pedido')),
            ],
        ),
    ]
