# Generated by Django 4.0.5 on 2022-06-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datoscliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datoscliente',
            old_name='rut',
            new_name='rutreg',
        ),
    ]
